### ISSUE TITLE
The route "undefined" does not exist.

### ISSUE THREAD

**Issue by jokari4242** [anis-marrouchi/UploadCropImageBundle#1]
Hello,

I'm trying to install the bundle but i have this error : The route "undefined" does not exist in router.js 
 when i'm using the demo at the url /upload.. If you have an idea for fix it. Thanks a lot!

**Comment by anis-marrouchi** [comment]
Hi jokari4242,
you will need to add the data-route attribute to the file field like so 

``` twig
 {{ form_widget(form.file, {'id':'file','data-route':'media_json_upload'})}}
  {{ form_widget(form.dimensions) }}
```
